PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> PREFIX dbo: <http://dbpedia.org/ontology/> PREFIX dbprop: <http://dbpedia.org/property/> PREFIX person: <http://dbpedia.org/ontology/Person/> SELECT ?name ?number ?birthdate ?clubname WHERE {{ ?soccerplayer rdf:type dbo:SoccerPlayer . ?soccerplayer dbprop:fullname ?name . ?soccerplayer person:birthDate ?birthdate . ?soccerplayer dbo:currentNumber ?number . ?club dbprop:league ?league . } }